name: cd

on:
  push:
    branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.0'

            - name: build
              run: 
                ./scripts/buildprod.sh
            
            - name: Deploy to cloud run
              run: 
                gcloud run deploy --image us-central1-docker.pkg.dev/notely-441610/notely-ar-repo/notely:latest \
                --region us-central1 --allow-unauthenticated --project notely-441610 --max-instances 4